channels:
- conda-forge

dependencies:
- python=3.12.10
- pip<=25.3

- pip:
  - mlflow==2.22.4
  - cloudpickle==3.1.2
  - numpy==2.3.5
  - pandas==2.3.3
  - psutil==7.1.3
  - pyarrow==19.0.1
  - scikit-learn==1.7.2
  - scipy==1.16.3

name: mlflow-env
